### ISSUE TITLE
Having problems while adding a pool (No module named concurrent.futures ?)

### ISSUE THREAD

**Issue by PedroMD** [Azure/batch-shipyard#102]
Hello everybody!

I'm having a hard time creating my first pool using batch-shipyard with a custom docker image. I've followed the steps at https://docs.microsoft.com/en-us/azure/batch/batch-account-create-portal#linked-azure-storage-account to create a Batch account using the `Batch service mode`. I did create a General Purpose Storage Account for this Batch Account only and I've added its name under the `account` json property and also its key. However, I'm getting this issue when deploying the pool:

```
Traceback (most recent call last):
  File "/home/pdiogo/batch-shipyard/shipyard.py", line 1530, in <module>
    cli()
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pdiogo/batch-shipyard/shipyard.py", line 1065, in pool_add
    ctx.queue_client, ctx.table_client, ctx.config)
  File "/home/pdiogo/batch-shipyard/convoy/fleet.py", line 2026, in action_pool_add
    batch_client, blob_client, config
  File "/home/pdiogo/batch-shipyard/convoy/fleet.py", line 931, in _add_pool
    blob_client, config, _rflist)
  File "/home/pdiogo/batch-shipyard/convoy/storage.py", line 335, in upload_resource_files
    _check_file_and_upload(blob_client, file, 'blob_resourcefiles')
  File "/home/pdiogo/batch-shipyard/convoy/storage.py", line 321, in _check_file_and_upload
    _STORAGE_CONTAINERS[container], file[0], str(file[1]))
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/azure/storage/blob/blockblobservice.py", line 406, in create_blob_from_path
    timeout=timeout)
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/azure/storage/blob/blockblobservice.py", line 550, in create_blob_from_stream
    initialization_vector=iv
  File "/home/pdiogo/batch-shipyard/shipyard.venv/local/lib/python2.7/site-packages/azure/storage/blob/_upload_chunking.py", line 71, in _upload_blob_chunks
    import concurrent.futures
ImportError: No module named concurrent.futures
```

Any idea what it might be? I don't need to add attached, but It looks like `storage` is not an optional field...

Thank you in advance.

Regards,
Pedro

**Comment by PedroMD** [comment]
Forgot to mention my batch account was created in "Batch service mode" and that my configuration was based on [this recipe](https://github.com/Azure/batch-shipyard/tree/master/recipes/Caffe-GPU)

The only difference regarding those .json is that I'm using a custom-built docker image and have deleted the 
```
 "ssh": {
            "username": "docker"
        },
```
from the `pool.json`, but it should be fine anyway because that seems to an optional field. 

Any thoughts on why it is failing?

**Comment by alfpark** [comment]
It appears you installed into a virtual environment. Can you perform the following:

```shell
source shipyard.venv/bin/activate
pip list
deactivate
```

and copy the output here? For some reason it could be that `futures` was not installed from the `azure-storage` dependency. If that is the case you can do:

```shell
source shipyard.venv/bin/activate
pip install futures
deactivate
```

To see if this resolves your issue.

**Comment by PedroMD** [comment]
Thank you @alfpark. Looks like pip installed `future`, but not `futures:

```
(shipyard.venv) pdiogo@nv-12-3:~/batch-shipyard$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
adal (0.4.5)
asn1crypto (0.22.0)
azure-batch (3.0.0)
azure-common (1.1.6)
azure-keyvault (0.3.0)
azure-mgmt-batch (4.0.0)
azure-mgmt-compute (1.0.0)
azure-mgmt-network (1.0.0)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-resource (1.1.0)
azure-nspkg (2.0.0)
azure-servicemanagement-legacy (0.20.5)
azure-storage (0.34.2)
blobxfer (0.12.1)
certifi (2017.4.17)
cffi (1.10.0)
click (6.7)
cryptography (1.9)
enum34 (1.1.6)
future (0.16.0)
idna (2.5)
ipaddress (1.0.18)
isodate (0.5.4)
keyring (10.4.0)
msrest (0.4.8)
msrestazure (0.4.7)
oauthlib (2.0.2)
pathlib2 (2.2.1)
pip (9.0.1)
pycparser (2.17)
PyJWT (1.5.2)
python-dateutil (2.6.0)
requests (2.14.2)
requests-oauthlib (0.8.0)
scandir (1.5)
SecretStorage (2.3.1)
setuptools (36.0.1)
six (1.10.0)
wheel (0.29.0)
(shipyard.venv) pdiogo@nv-12-3:~/batch-shipyard$ pip install futures
```

which is indeed in the requirements.txt:
`future==0.16.0`

Anyway, after manually installing `futures`, it all worked.

Thanks!

**Comment by alfpark** [comment]
`future` package is different than the `futures` package. `futures` is specified in the `azure-storage` requirements/setup.py as a dependency and should have been installed. I'm not sure why it was not installed for your environment.

Thanks for working through the issue.

For future reference, as stated in the installation docs - if you can install for Python3, it is recommended to do so instead of Python2.7. `futures` is not required for Python3 installs.
