### ISSUE TITLE
Trouble deploying NV* Instances

### ISSUE THREAD

**Issue by PedroMD** [Azure/batch-shipyard#119]
Hello all, 

I've been trying to deploy a NV12 instance, but I'm always getting an error.

```
2017-09-13 08:44:58.197 DEBUG - downloading NVIDIA driver to resources/nvidia-driver-grid.run
2017-09-13 08:45:36.704 DEBUG - wrote 79069931 bytes to resources/nvidia-driver-grid.run
Traceback (most recent call last):
  File "/opt/batch-shipyard/shipyard.py", line 1714, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/batch-shipyard/shipyard.py", line 1069, in pool_add
    ctx.table_client, ctx.config)
  File "/opt/batch-shipyard/convoy/fleet.py", line 2259, in action_pool_add
    batch_client, blob_client, config
  File "/opt/batch-shipyard/convoy/fleet.py", line 1176, in _add_pool
    batch_client, blob_client, config)
  File "/opt/batch-shipyard/convoy/fleet.py", line 866, in _construct_pool_object
    blob_client, config, pool_settings.vm_size)
  File "/opt/batch-shipyard/convoy/fleet.py", line 349, in _setup_nvidia_driver_package
    raise RuntimeError('sha256 mismatch for {}'.format(pkg))
RuntimeError: sha256 mismatch for /opt/batch-shipyard/resources/nvidia-driver-grid.run
```

I've tried to reference a different NVIDIA driver bit it also didn't work:
```json
 "nvidia_driver": {
            "source": "https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run"
        },
```
(pool.json)

Any reason why? NC instances work fine. 

Thank you.

**Comment by alfpark** [comment]
This is due to an underlying update in the GPU driver with an opaque forwarding URL. For a temporary workaround, place this in your `pool.json` for NV-series allocations:

```json
        "gpu": {
            "nvidia_driver": {
                "source": "https://go.microsoft.com/fwlink/?linkid=849941"
            }
        }
```

The SHA256 hash will be updated soon.

**Comment by PedroMD** [comment]
Thank you, it worked after pull the new docker image.

**Comment by tswc** [comment]
I have the same issue during using NC6.  
It is used to work with https://github.com/Azure/batch-shipyard/issues/119#issuecomment-329215262, but now it does not work any more

**Comment by alfpark** [comment]
This workaround is not necessary on the latest release. Please upgrade to the latest version and remove the workaround.
