### ISSUE TITLE
UnboundLocalError: local variable 'node_agent' referenced before assignment - when adding a job

### ISSUE THREAD

**Issue by fertinaz** [Azure/batch-shipyard#120]
Trying to use shipyard for our private openfoam registry. However I get the following error when I add a job: 

> UnboundLocalError: local variable 'node_agent' referenced before assignment

Pool is created successfully but jobs cannot be submitted. Here are the .json files.

crendential.json:
```json
"credentials": {
        "batch": {
            "account_key": "batch_account_key",
            "account_service_url": "batch_account_url"
        },
        "storage": {
            "mystorageaccount": {
                "account": "storage_account",
                "account_key": "storage_account_key",
                "endpoint": "core.windows.net"
            }
        },
        "docker_registry": {
            "registry.theubercloud.com": {
                "username": "myusername",
                "password": "mypassword"
            }
        }
    }
```

config.json
```json
{
    "batch_shipyard": {
        "storage_account_settings": "mystorageaccount"
    },
    "docker_registry": {
        "private": {
            "allow_public_docker_hub_pull_on_missing": true,
            "server": "registry.theubercloud.com"   
        }
    },
    "global_resources": {
        "docker_images": [
            "library_staging/openfoam_2.3.0_centos_6.5"
        ]
    }
}
```

jobs.json:
```json
{
    "job_specifications": [
        {
            "id": "jobopenfoam-ubercloud",
            "auto_complete": true,
            "environment_variables": {
                "storage_account_name": "mystorageaccountname",
                "storage_account_key": "mystorageaccountkey",
                "ENV_CLUSTER_DISCOVERY": "consul://url",
                "ENV_ROLE": "slave",
                "ENV_SSHD_PORT": "1022",
                "ENV_CUSTOMER_EMAIL": "fatih.ertinaz@theubercloud.com",
                "ENV_ORDER_NUMBER": "azurebatch"
            },
            "tasks": [
                {
                    "image": "library_staging/openfoam_2.3.0_centos_6.5",
                    "command": "/foam_app_bin/blockMesh -case /foam_tutorial_bin/motorBike",
                    "infiniband": true,
                    "multi_instance": {
                        "num_instances": "pool_current_dedicated",
                        "coordination_command": null
                    }
                }
            ]
        }
    ]
}
```

pool.json:
```json
{
    "pool_specification": {
        "id": "pool-openfoam-ubercloud",
        "vm_configuration": {
            "platform_image": {
                "publisher": "OpenLogic",
                "offer": "CentOS",
                "sku": "7.3"
            }
        },
        "vm_size": "STANDARD_A8",
        "vm_count": {
            "dedicated": 2
        },
        "inter_node_communication_enabled": true,
        "ssh": {
            "username": "docker"
        },
        "reboot_on_start_task_failed": false,
        "block_until_all_global_resources_loaded": true
    }
}
```

This is the entire log of the error output:

```
SHIPYARD_CONFIGDIR=recipes/OpenFOAM-UberCloud/config ./shipyard jobs add
2017-09-19 14:50:39.232 INFO - Adding job jobopenfoam-ubercloud to pool pool-openfoam-ubercloud
Traceback (most recent call last):
  File "/Users/fertinaz/batch-shipyard/shipyard.py", line 1714, in <module>
    cli()
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/fertinaz/batch-shipyard/shipyard.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/fertinaz/batch-shipyard/shipyard.py", line 1355, in jobs_add
    ctx.table_client, ctx.keyvault_client, ctx.config, recreate, tail)
  File "/Users/fertinaz/batch-shipyard/convoy/fleet.py", line 2721, in action_jobs_add
    _JOBPREP_FILE, _BLOBXFER_FILE, recreate, tail)
  File "/Users/fertinaz/batch-shipyard/convoy/batch.py", line 3379, in add_jobs
    cloud_pool, config, pool, jobspec, _task, missing_images)
  File "/Users/fertinaz/batch-shipyard/convoy/settings.py", line 2776, in task_settings
    node_agent.startswith('batch.node.centos')):
UnboundLocalError: local variable 'node_agent' referenced before assignment
```

An interesting detail is that when I try to delete this job, shipyard does not complain that job doesn't exist. It successfully deletes the job. 

Below shows that (I presume) container image is pulled without any problems and I can ssh to the container image.

```
fatih@8a5b5c87faff4cb6b7ee1f50c7b7745b000000:~$ sudo docker images
REPOSITORY                                                            TAG                 IMAGE ID            CREATED             SIZE
library_staging/openfoam_2.3.0_centos_6.5                             latest              e33c5f9ade54        11 hours ago        6.7GB
sudo docker run -it e33c5f9ade54 bash
[root@699bc506f4c1 /]# ls
bin   dev  home  lib64       media  opt   root  selinux  sys  usr
boot  etc  lib   lost+found  mnt    proc  sbin  srv      tmp  var
[root@699bc506f4c1 /]# cd opt/
OpenFOAM-2.3.0/           qt-4.8/                   ThirdParty-2.3.0/
OpenFOAM-ParaView-3.12.0/ rh/                       ThirdParty-2.3.0.tgz
```

**Comment by alfpark** [comment]
`pool.json` has:

```
            "platform_image": {
                "publisher": "OpenLogic",
                "offer": "CentOS",
                "sku": "7.3"
            }
```

while the `jobs.json` has:

```
            "tasks": [
                {
                    "image": "library_staging/openfoam_2.3.0_centos_6.5",
                    "command": "/foam_app_bin/blockMesh -case /foam_tutorial_bin/motorBike",
                    "infiniband": true,
                    "multi_instance": {
                        "num_instances": "pool_current_dedicated",
                        "coordination_command": null
                    }
                }
            ]
```

You cannot specify `"infiniband": true` without an HPC image. Please change your `pool.json` to:

```
            "platform_image": {
                "publisher": "OpenLogic",
                "offer": "CentOS-HPC",
                "sku": "7.3"
            }
```

and recreate your pool.

**Comment by fertinaz** [comment]
Yes I just saw it in the Python code a few minutes ago. 
``` Python

        # only centos-hpc and sles-hpc:12-sp1 are supported
        # for infiniband
        if (publisher == 'openlogic' and offer == 'centos-hpc' or
                node_agent.startswith('batch.node.centos')):
            run_opts.append('-v /etc/rdma:/etc/rdma:ro')
            run_opts.append('-v /etc/rdma/dat.conf:/etc/dat.conf:ro')
```
