### ISSUE TITLE
Batch account_key needs to be defined even if account_key_keyvault_secret_id is set

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#13]
I'm trying to use `credentials.json` with KeyVault to just store secret IDs, and provide the KeyVault parameters through environment vars.

When using `credentials.json` this way, it appears that the `credentials.batch.account_key` needs to exist even if `credentials.batch.account_key_keyvault_secret_id` is set. If it doesn't exist, then shipyard assumes that the credentials.json is bad and tries to retrieve it from the secret storage, which will fail if the credential secret id is not set. Since I'm using `credentials.json` in my repository, rather than a KeyVault `credentials.json`, this throws many exceptions.

```
convoy.keyvault:fetch_credentials_json:140 fetching credentials json from keyvault
Traceback (most recent call last):
  File "/mnt/batch-shipyard/shipyard.py", line 183, in _init_config
    convoy.settings.credentials_batch(self.config)
  File "/mnt/batch-shipyard/convoy/settings.py", line 592, in credentials_batch
    account_key=conf['account_key'],
KeyError: 'account_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/azure/keyvault/key_vault_id.py", line 33, in _validate_string_argument
    prop = prop.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch-shipyard/shipyard.py", line 919, in <module>
    cli()
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/batch-shipyard/shipyard.py", line 535, in keyvault_list
    ctx.initialize(creds_only=True, no_config=True)
  File "/mnt/batch-shipyard/shipyard.py", line 93, in initialize
    self._init_config(creds_only)
  File "/mnt/batch-shipyard/shipyard.py", line 192, in _init_config
    self.keyvault_credentials_secret_id)
  File "/mnt/batch-shipyard/convoy/fleet.py", line 265, in fetch_credentials_json_from_keyvault
    keyvault_client, keyvault_uri, keyvault_credentials_secret_id)
  File "/mnt/batch-shipyard/convoy/keyvault.py", line 141, in fetch_credentials_json
    cred = client.get_secret(keyvault_credentials_secret_id)
  File "/home/user/.local/lib/python3.5/site-packages/azure/keyvault/key_vault_client.py", line 135, in get_secret
    sid = parse_secret_id(secret_identifer)
  File "/home/user/.local/lib/python3.5/site-packages/azure/keyvault/key_vault_id.py", line 142, in parse_secret_id
    return parse_object_id('secrets', id)
  File "/home/user/.local/lib/python3.5/site-packages/azure/keyvault/key_vault_id.py", line 79, in parse_object_id
    id = _validate_string_argument(id, 'id')
  File "/home/user/.local/lib/python3.5/site-packages/azure/keyvault/key_vault_id.py", line 36, in _validate_string_argument
    raise TypeError("argument '{}' must by of type string".format(name))
TypeError: argument 'id' must by of type string
```

If I add a blank `account_key` property, then everything seems to work fine:

```json
{
    "credentials": {
        "batch": {
            "account": "mybatchaccount",
            "account_key": "",
            "account_key_keyvault_secret_id": "https://myvault.vault.azure.net/secrets/batchkey",
            "account_service_url": "https://mybatchaccount.region.batch.azure.com"
        }
    }
}
```

Is this intended behavior? The documentation seems to suggest that, if I define a particular `*_keyvault_secret_id` property, then I can omit the `*` property itself. The other storage and docker registry `*_keyvault_secret_id` properties seem to read fine without needing to define their corresponding `*`s.

Thanks!

**Comment by alfpark** [comment]
@lediur `account_key` should not need to be defined at all, your assumption is correct. I've identified the issue and will have a fix in the next release. Please use your workaround in the meantime.
