### ISSUE TITLE
On Windows 10 ssh keys are not found

### ISSUE THREAD

**Issue by CharlesCara** [Azure/batch-shipyard#152]
This might be more of a documentation issue, but on Windows 10 the ssh public and private keys are not found when creating and using a pool.  

I have saved the public and private keys in C:\Users\MyName\.ssh\
In config/pool.yaml the lines are 
```
  ssh:
    username: shipyard
    ssh_public_key: C:\Users\CharlesC\.ssh\id_rsa.pub
    ssh_private_key: C:\Users\CharlesC\.ssh\id_rsa

```
However, when I run shipyard from Windows cmd terminal, I get:
```
2018-01-10 14:17:20.864 INFO - executing command on node 52.232.100.140:50000 with key C:\Users\CharlesC\.ssh\id_rsa
Traceback (most recent call last):
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.py", line 1764, in <module>
    cli()
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\shipyard.py", line 1253, in images_list
    convoy.fleet.action_pool_images_list(ctx.batch_client, ctx.config)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\convoy\fleet.py", line 2920, in action_pool_images_list
    _list_docker_images(batch_client, config)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\convoy\fleet.py", line 1867, in _list_docker_images
    '"{{.ID}} {{.Repository}}:{{.Tag}}"'
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\convoy\crypto.py", line 176, in connect_or_exec_ssh_command
    ssh_cmd, shell=shell, pipe_stderr=True)
  File "C:\Users\CharlesC\Documents\azure\batch-shipyard\convoy\util.py", line 461, in subprocess_nowait_pipe_stdout
    cwd=cwd, env=env)
  File "C:\Python\Python36-32\Lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python36-32\Lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`
```

I am able to configure the ssh access successfully on mac and linux machines.

**Comment by alfpark** [comment]
Do you have a typo in your config?:

```
ssh_public_key: C:\Users\C\.ssh\id_rsa.pub
```

**Comment by CharlesCara** [comment]
Thanks - the typo was when I copied it into the webpage (now corrected).   The problem was `ssh.exe` not being on my path.
