### ISSUE TITLE
Credentials error

### ISSUE THREAD

**Issue by svaj** [Azure/batch-shipyard#157]
After initially failing to install locally on OS X (the install complained about missing pythong modules azure.cosmosdb, etc), I installed the docker image and created a configdir with the config,credentials,jobs, and pool yaml files (I used the guide at http://batch-shipyard.readthedocs.io/en/latest/05-batch-shipyard-from-scratch-step-by-step/).  When I attempt to invoke shipyard it fails.  
```
shipyard pool list --show-config --configdir config
Traceback (most recent call last):
  File "/opt/batch-shipyard/shipyard.py", line 1764, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/batch-shipyard/shipyard.py", line 1086, in pool_list
    ctx.initialize_for_batch()
  File "/opt/batch-shipyard/shipyard.py", line 122, in initialize_for_batch
    self.keyvault_client = convoy.clients.create_keyvault_client(self)
  File "/opt/batch-shipyard/convoy/clients.py", line 211, in create_keyvault_client
    kv = settings.credentials_keyvault(ctx.config)
  File "/opt/batch-shipyard/convoy/settings.py", line 1262, in credentials_keyvault
    config['credentials'],
KeyError: 'credentials'
```
Am I missing something obvious to get up and running?

**Comment by alfpark** [comment]
This means that the yaml config files are not where the tool expects them to be (or your credentials file is malformed). Are your `.yaml` files in the `config` dir where you are executing `shipyard`? Note that if you created your config files on the host, these files will not automatically appear in the container filesystem when you are executing the Docker-based CLI; you will need to pass a `-v` argument. Please see [this relevant section](https://github.com/Azure/batch-shipyard/blob/master/docs/20-batch-shipyard-usage.md#batch-shipyard-container-image-cli-invocation) in the CLI Usage docs.

I'll try to see if I can repro the Mac OS X installation issue you are facing.

**Comment by alfpark** [comment]
I cannot repro Mac OS X installation problems when using the `install.sh` helper script; here are the [Mac OS X installation instructions](http://batch-shipyard.readthedocs.io/en/latest/01-batch-shipyard-installation/#mac-install).

**Comment by svaj** [comment]
Ah, using -v worked!  Thanks

Also, I missed the `-e shipyard.venv` argument when installing locally -- that worked too!

Thanks again!
