### ISSUE TITLE
Exception when providing job environment variables without task environment variables

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#16]
If my `jobs.json` file contains an `environment_variables` property in a job specification object, but no task-level property, I get the following exception:

```
Traceback (most recent call last):
  File "/mnt/batch-shipyard/shipyard.py", line 919, in <module>
    cli()
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/batch-shipyard/shipyard.py", line 739, in jobs_add
    ctx.batch_client, ctx.blob_client, ctx.config, recreate, tail)
  File "/mnt/batch-shipyard/convoy/fleet.py", line 1451, in action_jobs_add
    recreate, tail)
  File "/mnt/batch-shipyard/convoy/batch.py", line 1742, in add_jobs
    job_env_vars, task.environment_variables)
  File "/mnt/batch-shipyard/convoy/util.py", line 199, in merge_dict
    raise ValueError('dict1 or dict2 is not a dictionary')
ValueError: dict1 or dict2 is not a dictionary
```

Seems like https://github.com/Azure/batch-shipyard/blob/master/convoy/batch.py#L1738 checks for the task-but-no-job case, but not the job-but-no-task case.

**Comment by alfpark** [comment]
Thanks for reporting this, it'll be fixed in the next release.
