### ISSUE TITLE
Updating images from azure function

### ISSUE THREAD

**Issue by svaj** [Azure/batch-shipyard#167]
I'm using the azure functions site extension and am able to run most shipyard commands.  When I go to update images on my nodes, I end up with a python stack trace.  When I run the same `shipyard pool images update` locally, I am able to update the images there.  Is this functionality available in azure functions?

Here is the stack trace from running in the function:
2018-02-23T19:11:00.389 [Info] Updating shipyard pool with latest images..
2018-02-23T19:11:21.390 [Info] 2018-02-23 19:11:20.342 DEBUG - forcing update via SSH due to low priority nodes
2018-02-23 19:11:20.953 INFO - executing command on node 137.117.9.214:50000 with key D:\home\site\wwwroot\shipyard\id_rsa_shipyard
Traceback (most recent call last):
  File "D:\home\batch-shipyard\shipyard.py", line 1796, in <module>
    cli()
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:\home\python362x64\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "D:\home\python362x64\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:\home\batch-shipyard\shipyard.py", line 1273, in images_update
    singularity_image, ssh)
  File "D:\home\batch-shipyard\convoy\fleet.py", line 2895, in action_pool_images_update
    singularity_image, force_ssh=ssh)
  File "D:\home\batch-shipyard\convoy\fleet.py", line 1688, in _update_container_images
    _update_container_images_over_ssh(batch_client, config, pool, coordcmd)
  File "D:\home\batch-shipyard\convoy\fleet.py", line 1539, in _update_container_images_over_ssh
    ssh_private_key, username, sync=False, command=command))
  File "D:\home\batch-shipyard\convoy\crypto.py", line 176, in connect_or_exec_ssh_command
    ssh_cmd, shell=shell, pipe_stderr=True)
  File "D:\home\batch-shipyard\convoy\util.py", line 461, in subprocess_nowait_pipe_stdout
    cwd=cwd, env=env)
  File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.2\tools\Lib\subprocess.py", line 707, in __init__
  File "D:\Repos\azure-python-siteextensions\source_packages\python.3.6.2\tools\Lib\subprocess.py", line 992, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by alfpark** [comment]
This is the relevant bit:
```
2018-02-23T19:11:21.390 [Info] 2018-02-23 19:11:20.342 DEBUG - forcing update via SSH due to low priority nodes
```

As there is no `ssh.exe` installed by default on an Azure App Service environment, this will fail. You can try grabbing a [Windows version of ssh](https://github.com/PowerShell/Win32-OpenSSH/releases) and placing it in `%PATH%` (or where you execute `shipyard.cmd` from).

**Comment by svaj** [comment]
That worked!
