### ISSUE TITLE
AuthorizationFailure accessing secured storage account from virtual network

### ISSUE THREAD

**Issue by dbradnum** [Azure/batch-shipyard#203]
Hi,

I'm trying to get Batch Shipyard working with my own virtual network and subnet, with worker nodes connecting through to a storage account that is secured to that subnet. Have been following the instructions [here](http://batch-shipyard.readthedocs.io/en/latest/64-batch-shipyard-byovnet/) , but falling at the final hurdle. I'm not sure whether this is a bug, or I'm missing something - would really appreciate some help if so.

If I leave the storage account with default security settings, everything works perfectly. I can create a pool with no problem, workers are created in the correct subnet, and their tasks read and write files from/to blob containers in the storage account. However, when I restrict access to the storage account down to just the subnet referenced in my pool config, I see the following error when submitting jobs:

```
2018-06-01 22:56:28.956 DEBUG - batch account key not specified, using aad auth
2018-06-01 22:56:29.721 INFO - Adding job testJob to pool shipyardTestSecure
Traceback (most recent call last):
<full stack removed>
  File "C:\Users\djb72\batch-shipyard\convoy\storage.py", line 184, in create_blob_container_saskey
    blob_client.create_container(container, fail_on_exist=False)
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\blob\baseblobservice.py", line 621, in create_container
    _dont_fail_on_exist(ex)
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\common\_error.py", line 92, in _dont_fail_on_exist
    raise error
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\blob\baseblobservice.py", line 618, in create_container
    self._perform_request(request)
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\common\storageclient.py", line 354, in _perform_request
    raise ex
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\common\storageclient.py", line 289, in _perform_request
    raise ex
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\common\storageclient.py", line 275, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "C:\Users\djb72\batch-shipyard\shipyard.venv\lib\site-packages\azure\storage\common\_error.py", line 111, in _http_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: This request is not authorized to perform this operation.ErrorCode: AuthorizationFailure
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:526b8bcc-d01e-0058-4ff3-f98d55000000
Time:2018-06-01T21:56:31.0113595Z</Message></Error>
```
Further details of my setup:
- I'm using Batch Shipyard version 3.4.0
- Credentials setup looks like this, using a service principal. I also have two separate storage accounts - one for batch to use for machine images etc, and one for my data. It's the latter I want to secure.
```
credentials:  
  aad:
    directory_id: <snipped>
    application_id: <snipped>
    auth_key: <snipped>
  batch:
    account_service_url: <snipped>
  storage:
    mtcstorageaccount:
      account: <snipped>
      account_key: <snipped>
      endpoint: core.windows.net
    batchstorageaccount:
      account: <snipped>
      account_key: <snipped>
      endpoint: core.windows.net
```
- the application linked in the aad credentials has the `Virtual Machine Contributor` role on the subnet, `Contributor `on the Batch account and `Contributor `role on the storage account (perhaps unnecessarily?)
- pool config just includes `arm_subnet_id` (referring to the relevant subnet) under the virtual_network section
- the subnet has a service endpoint for storage, and has no network security group attached
- all resources are under the same resource group, and in the same region
- the batch account is set up to use Batch Service allocation mode.

What am I missing?!

thanks,
David

**Comment by alfpark** [comment]
Are you running your command from a VM on the restricted subnet within the VNet? This is required if you restrict your storage account to access from only a specific VNet and your tasks specify environment variables, use IB/RDMA or GPUs (because an environment file must be uploaded to storage).

**Comment by dbradnum** [comment]
No, I wasn't - but that fixes the problem. Thanks!

In fact for my use-case, I only needed to run shipyard from a machine within the VNet (not necessarily the specific subnet), since I'm not using any of the features you listed.  Stupidly, though, I'd not even considered the connection from the client machine to storage and was running a small test VM on a separate VNet. 

Thanks again for the help.
