### ISSUE TITLE
cannot specify all start task failed nodes or unusable with a specific node id

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#249]
#### Problem Description
  File "convoy/batch.py", line 825, in wait_for_pool_ready
  File "convoy/batch.py", line 680, in _block_for_nodes_ready
RuntimeError: Please inspect both the node status above and files found within the caffe-cpu/<nodes>/startup directory (in the current working directory) if available. If this error appears non-transient, please submit an issue on GitHub, if not you can delete these nodes with "pool nodes del --all-start-task-failed" first prior to the resize operation.
[30591] Failed to execute script shipyard

veon@ubuntu:~/work/InvoiceRecognition/services/config$ ../batch-shipyard-3.6.1-cli-linux-x86_64 pool nodes del --all-start-task-failed
Traceback (most recent call last):
  File "shipyard.py", line 2812, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 1815, in nodes_del
  File "convoy/fleet.py", line 3576, in action_pool_nodes_del
ValueError: cannot specify all start task failed nodes or unusable with a specific node id
[30682] Failed to execute script shipyard

#### Batch Shipyard Version
3.6.1

#### Steps to Reproduce
just tried to run my pool

#### Expected Results
be able to clean up pool using command in the error message

#### Actual Results
cannot specify all start task failed nodes or unusable with a specific node id

**Comment by alfpark** [comment]
This issue was identified and fixed in `develop`.

Workarounds:

1. Delete nodes using Batch Explorer or the Portal.
2. Delete the entire pool.
