### ISSUE TITLE
mount error(2): No such file or directory

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#250]
#### Problem Description
unable to start pool

#### Batch Shipyard Version
3.6.1

#### Steps to Reproduce
batch-shipyard-3.6.1-cli-linux-x86_64 pool add

#### Additional Logs
```
veon@ubuntu:~/work/InvoiceRecognition/services/config$ ../batch-shipyard-3.6.1-cli-linux-x86_64 pool add
2018-12-17 04:45:28.337 INFO - creating container: shipyardgr-training-ub1
2018-12-17 04:45:28.669 INFO - creating container: shipyardrf-training-ub1
2018-12-17 04:45:28.730 INFO - creating container: shipyardtor-training-ub1
2018-12-17 04:45:28.790 INFO - creating table: shipyarddht
2018-12-17 04:45:29.196 INFO - creating table: shipyardtorrentinfo
2018-12-17 04:45:29.327 INFO - creating table: shipyardimages
2018-12-17 04:45:29.458 INFO - creating table: shipyardgr
2018-12-17 04:45:29.588 INFO - deleting blobs: shipyardgr-training-ub1
2018-12-17 04:45:29.688 INFO - deleting blobs: shipyardrf-training-ub1
2018-12-17 04:45:29.788 INFO - deleting blobs: shipyardtor-training-ub1
2018-12-17 04:45:29.885 DEBUG - clearing table (pk=training$ub1): shipyarddht
2018-12-17 04:45:29.983 DEBUG - clearing table (pk=training$ub1): shipyardtorrentinfo
2018-12-17 04:45:30.040 DEBUG - clearing table (pk=training$ub1): shipyardimages
2018-12-17 04:45:30.136 DEBUG - clearing table (pk=training$ub1): shipyardgr
2018-12-17 04:45:30.197 DEBUG - clearing table (pk=training$ub1): shipyardperf
2018-12-17 04:45:30.258 INFO - adding global resource: docker:u4basiccontainerregistry.azurecr.io/invoice-recognition/sql-data-extractor hash=ee32bdb660ebe063ad9b1449585bd07b6d3e5970
2018-12-17 04:45:31.090 DEBUG - autoscale enabled: False
2018-12-17 04:45:31.090 DEBUG - no virtual network settings specified
2018-12-17 04:45:31.299 INFO - deploying vm config: {'additional_properties': {}, 'publisher': 'Canonical', 'offer': 'UbuntuServer', 'sku': '16.04-LTS', 'version': 'latest', 'virtual_machine_image_id': None}
2018-12-17 04:45:31.353 INFO - uploading file /tmp/_MEI2Nnova/scripts/registry_login.sh as 'registry_login.sh'
2018-12-17 04:45:31.517 INFO - uploading file /tmp/_MEI2Nnova/scripts/shipyard_blobxfer.sh as 'shipyard_blobxfer.sh'
2018-12-17 04:45:31.681 INFO - uploading file /tmp/_MEI2Nnova/scripts/wait_for_images.sh as 'wait_for_images.sh'
2018-12-17 04:45:31.845 INFO - uploading file /tmp/batch-shipyard-3.6.1-resources/azurefile-mount-training-ub1.sh as 'azurefile-mount.sh'
2018-12-17 04:45:32.032 INFO - uploading file /tmp/_MEI2Nnova/scripts/shipyard_nodeprep.sh as 'shipyard_nodeprep.sh'
2018-12-17 04:45:32.240 INFO - Attempting to create pool: ub1
2018-12-17 04:45:32.556 INFO - Created pool: ub1
2018-12-17 04:45:32.557 DEBUG - waiting for all nodes in pool ub1 to reach one of: frozenset({<ComputeNodeState.idle: 'idle'>, <ComputeNodeState.preempted: 'preempted'>, <ComputeNodeState.unusable: 'unusable'>, <ComputeNodeState.start_task_failed: 'starttaskfailed'>})
2018-12-17 04:45:53.663 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=resizing allocation_state_transition_time=2018-12-17 12:45:32.502988+00:00]
2018-12-17 04:46:14.445 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=resizing allocation_state_transition_time=2018-12-17 12:45:32.502988+00:00]
2018-12-17 04:46:35.268 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=resizing allocation_state_transition_time=2018-12-17 12:45:32.502988+00:00]
2018-12-17 04:46:55.992 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=steady allocation_state_transition_time=2018-12-17 12:46:47.555483+00:00]
2018-12-17 04:46:55.992 DEBUG - tvm-2878057307_1-20181217t124646z: starting
2018-12-17 04:47:16.633 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=steady allocation_state_transition_time=2018-12-17 12:46:47.555483+00:00]
2018-12-17 04:47:16.634 DEBUG - tvm-2878057307_1-20181217t124646z: starting
2018-12-17 04:47:37.383 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=steady allocation_state_transition_time=2018-12-17 12:46:47.555483+00:00]
2018-12-17 04:47:37.384 DEBUG - tvm-2878057307_1-20181217t124646z: starting
2018-12-17 04:47:58.160 DEBUG - waiting for 1 dedicated nodes and 0 low priority nodes of size standard_d1_v2 to reach desired state in pool ub1 [resize_timeout=0:15:00 allocation_state=steady allocation_state_transition_time=2018-12-17 12:46:47.555483+00:00]
2018-12-17 04:47:58.160 DEBUG - tvm-2878057307_1-20181217t124646z: starting
2018-12-17 04:48:05.073 DEBUG - listing nodes in start task failed state
2018-12-17 04:48:05.073 INFO - compute nodes for pool ub1 (filters: start_task_failed=True unusable=False)
* node id: tvm-2878057307_1-20181217t124646z
  * state: starttaskfailed @ 2018-12-17 12:48:03.442811+00:00
  * allocation time: 2018-12-17 12:46:46.965596+00:00
  * last boot time: 2018-12-17 12:48:02.364490+00:00
  * scheduling state: enabled
  * agent:
    * version: 1.4.7
    * last update time: 2018-12-17 12:48:02.364490+00:00
  * no errors
  * start task:
    * failure info: usererror
      * FailureExitCode: The task exited with an exit code representing a failure
        * Message: The task exited with an exit code representing a failure
  * vm size: standard_d1_v2
  * dedicated: True
  * ip address: 10.0.0.4
  * running tasks: 0
  * total tasks run: 0
  * total tasks succeeded: 0
2018-12-17 04:48:05.073 ERROR - Detected start task failure, attempting to retrieve files for error diagnosis from nodes
2018-12-17 04:48:05.303 DEBUG - downloading files to ub1/tvm-2878057307_1-20181217t124646z
2018-12-17 04:48:06.010 INFO - all files retrieved from pool=ub1 node=tvm-2878057307_1-20181217t124646z include=startup/std*.txt
2018-12-17 04:48:06.010 DEBUG - downloading files to ub1/tvm-2878057307_1-20181217t124646z
2018-12-17 04:48:06.350 ERROR - no files found for pool ub1 node tvm-2878057307_1-20181217t124646z include=startup/wd/cascade.log
Traceback (most recent call last):
  File "shipyard.py", line 2812, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 1453, in pool_add
  File "convoy/fleet.py", line 3199, in action_pool_add
  File "convoy/fleet.py", line 1811, in _add_pool
  File "convoy/batch.py", line 887, in create_pool
  File "convoy/batch.py", line 825, in wait_for_pool_ready
  File "convoy/batch.py", line 680, in _block_for_nodes_ready
RuntimeError: Please inspect both the node status above and files found within the ub1/<nodes>/startup directory (in the current working directory) if available. If this error appears non-transient, please submit an issue on GitHub, if not you can delete these nodes with "pool nodes del --all-start-task-failed" first prior to the resize operation.
[31049] Failed to execute script shipyard
```

startup/stdout.txt
```
Linux 2d91924153c746b6aec515f80b78545d000000 4.15.0-1035-azure #36~16.04.1-Ubuntu SMP Fri Nov 30 15:25:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
2018-12-17T12:48:02,722868981+00:00 - INFO - Prep start
Configuration:
--------------
Custom image: 0
Native mode: 0
OS Distribution: ubuntu 16.04
Batch Shipyard version: 3.6.1
Blobxfer version: 1.5.5
Singularity version: 
User mountpoint: /mnt
Mount path: /mnt/batch/tasks/mounts
Prometheus: NE=, CA=,
Network optimization: 0
Encryption cert thumbprint: 
Install Kata Containers: 0
Default container runtime: runc
Install BeeGFS BeeOND: 0
Storage cluster mount: 
Custom mount: 
Install LIS: 
GPU: 
Azure Blob: 0
Azure File: 1
GlusterFS on compute: 0
HPN-SSH: 0
Enable Azure Batch group for Docker access: 
Fallback registry: 
Docker image preload delay: 0
Cascade via container: 1
P2P: 0
Block on images: u4basiccontainerregistry.azurecr.io/invoice-recognition/sql-data-extractor#

2018-12-17T12:48:02,774601439+00:00 - INFO - LIS installation not required
2018-12-17T12:48:02,776559053+00:00 - INFO - Mounting Azure File Shares
```

startup/stderr.txt
```
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

#### Additonal Comments
but I don't have any CIFS volume in configs...

**Comment by alfpark** [comment]
Can you please post your `config.yaml`?

**Comment by veonua** [comment]
```
batch_shipyard:
  storage_account_settings: mystorageaccount 
global_resources:
  additional_registries:
    docker:
    - u4basiccontainerregistry.azurecr.io
  docker_images:
  - u4basiccontainerregistry.azurecr.io/invoice-recognition/sql-data-extractor
  volumes:
    shared_data_volumes:
      azurefile_vol:
        volume_driver: azurefile
        storage_account_settings: mystorageaccount
        azure_file_share_name: myfileshare
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azfile
        mount_options:
        - file_mode=0777
        - dir_mode=0777
        bind_options: rw
```
        
when I comment out shared_data_volumes section deploy works.

**Comment by veonua** [comment]
ok, issue is in

azure_file_share_name: myfileshare
it must exist on the storage, before script run.

expected behavior - script either validates pre-requirements in the beginning or creates new share if it's not exists

**Comment by alfpark** [comment]
This behavior is already documented.

**Comment by veonua** [comment]
validation would be great to have
