### ISSUE TITLE
task factory must be much more verbose

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#254]
#### Feature Request Description
I'm trying to run task factory out of azure_storage, I have like 50k+ files to process.
in case I do any error in configuration I'd get error text too late, like I have to wait 
7 minutes just to get first line "INFO - Adding job <name> to pool <extr1>"
supposing batch shipyard scans my Azure Files in one thread.
Then 2 minutes waiting for something. 
Just to find out that there would be 0 jobs spawned

```
../batch-shipyard-3.6.1-cli-linux-x86_64 jobs add --tail stdout.txt
2018-12-20 06:13:18.886 INFO - Adding job ocrjob to pool extr1
2018-12-20 06:15:20.200 INFO - submitted all 0 tasks to job ocrjob
2018-12-20 06:15:20.201 DEBUG - attempting to stream file stdout.txt from job=ocrjob task=None
Traceback (most recent call last):
  File "shipyard.py", line 2812, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 1863, in jobs_add
  File "convoy/fleet.py", line 3789, in action_jobs_add
  File "convoy/batch.py", line 5418, in add_jobs
  File "convoy/batch.py", line 3215, in stream_file_and_wait_for_task
  File "site-packages/azure/batch/operations/file_operations.py", line 338, in get_properties_from_task
azure.batch.models.batch_error_py3.BatchErrorException: Operation returned an invalid status code 'The specified task does not exist.'
[19115] Failed to execute script shipyard
```

#### Describe Preferred Solution
it would be nice to get more feedback and some estimation of the process

#### Describe Alternatives Considered
also maybe run this work in azure to speed up file search process?

**Comment by alfpark** [comment]
Adding more verbosity to the task factory process will be merged in the next release.
