### ISSUE TITLE
No such file or directory: '/tmp/_MEIhjVTEH/federation/docker-compose.yml'

### ISSUE THREAD

**Issue by veonua** [Azure/batch-shipyard#258]
#### Problem Description
batch-shipyard fed proxy create
2018-12-31 17:12:25.392 DEBUG - checking if federation proxy exists
Confirm create federation proxy [y/n]: y
2018-12-31 17:12:29.761 DEBUG - resource group oslo-PeoplePlatform-AzureBatch exists
2018-12-31 17:12:29.762 INFO - creating container: shipyardfedglobal
2018-12-31 17:12:30.089 INFO - creating table: shipyardfedglobal
2018-12-31 17:12:30.446 INFO - creating table: shipyardfedjobs
2018-12-31 17:12:30.951 DEBUG - remote file is the same for shipyard_federation_bootstrap.sh, skipping
2018-12-31 17:12:30.996 INFO - uploading file /tmp/_MEIhjVTEH/federation/docker-compose.yml as'docker-compose.yml'
Traceback (most recent call last):
  File "shipyard.py", line 2812, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 2491, in fed_proxy_create
  File "convoy/fleet.py", line 4559, in action_fed_proxy_create
  File "convoy/federation.py", line 203, in create_federation_proxy
  File "convoy/storage.py", line 1821, in upload_for_nonbatch
  File "convoy/storage.py", line 1754, in _check_file_and_upload
  File "site-packages/azure/storage/blob/blockblobservice.py", line 446, in create_blob_from_path
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIhjVTEH/federation/docker-compose.yml'
[9058] Failed to execute script shipyard

#### Batch Shipyard Version
3.6.1

#### Steps to Reproduce
batch-shipyard fed proxy create

#### Expected Results
fed proxy created

**Comment by alfpark** [comment]
As a workaround, please use an alternative to the binary distribution while a fix is prepared for release.
