### ISSUE TITLE
Git Clone error Azure Function site extension

### ISSUE THREAD

**Issue by rikroe** [Azure/batch-shipyard#260]
Hi, 
when trying to install Batch Shipyard to an Azure Function, I'm getting a weird Access Denied error in git clone....
This is the output of Kudu:

ExitCode: 1, Output: D:\\Program Files\\Git\\cmd\\git.exe
D:\\Program Files\\Git\\bin\\git.exe
D:\\Program Files\\Git\\mingw64\\bin\\git.exe
\"Batch Shipyard tag ??3\"
\"Could not git clone to tag ??3 at D:\\home\\batch-shipyard\", Error: Access is denied.
Cloning into 'D:\\home\\batch-shipyard'...
warning: Could not find remote branch ��3 to clone.
fatal: Remote branch ��3 not found in upstream origin, Kudu.Core.Infrastructure.CommandLineException: Access is denied.
Cloning into 'D:\\home\\batch-shipyard'...
warning: Could not find remote branch ��3 to clone.
fatal: Remote branch ��3 not found in upstream origin
D:\\home\\SiteExtensions\\BatchShipyard\\install.cmd 
   at Kudu.Core.Infrastructure.Executable.ExecuteInternal(ITracer tracer, Func`2 onWriteOutput, Func`2 onWriteError, Encoding encoding, String arguments, Object[] args) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\Executable.cs:line 235
   at Kudu.Core.Infrastructure.Executable.ExecuteWithProgressWriter(ILogger logger, ITracer tracer, String arguments, Object[] args) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\Executable.cs:line 137
   at Kudu.Core.SiteExtensions.SiteExtensionManager.<>c__DisplayClass27_1.<InstallExtension>b__1() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManager.cs:line 537
   at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass2_0.<Attempt>b__0() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 16
   at Kudu.Core.Infrastructure.OperationManager.Attempt[T](Func`1 action, Int32 retries, Int32 delayBeforeRetry, Func`2 shouldRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 42
   at Kudu.Core.Infrastructure.OperationManager.Attempt(Action action, Int32 retries, Int32 delayBeforeRetry) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Infrastructure\\OperationManager.cs:line 14
   at Kudu.Core.SiteExtensions.SiteExtensionManager.<InstallExtension>d__27.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManager.cs:line 550
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Kudu.Core.SiteExtensions.SiteExtensionManager.<TryInstallExtension>d__26.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SiteExtensions\\SiteExtensionManager.cs:line 335

**Comment by alfpark** [comment]
It's possible that a branch was getting force pushed at the same time you were cloning. Can you try re-running the install? You may need to perform it manually (see the docs).

**Comment by rikroe** [comment]
I can't do a manual install from D:\home\SiteExtensions\BatchShipyard as nothing gets cloned - I've tried a couple of times during the day. It's weird as apparently git (started by kudu/nuget) is unable to find the respective branch at the remote (presumably github).

Would a fully manual install (manual git clone from master and then following the Azure Functions instructions work)?

**Comment by alfpark** [comment]
Sorry, I missed this:

```
"Batch Shipyard tag ??3"
```

That's an invalid tag. It might have something to do with the fact that the version.txt file in the Nuget package is encoded as UCS-2 LE BOM and perhaps a change happened with the site extension installer environment.

I'll see if I can force ASCII/UTF-8 encoding for the `version.txt` file generated with the extension package.

In the meantime, you can delete the `version.txt` file in `D:\home\SiteExtensions\BatchShipyard` and create a new file `version.txt` with the text `3.6.1` (with no newline).
