### ISSUE TITLE
If task name is too long, fails to add task

### ISSUE THREAD

**Issue by andreadotti** [Azure/batch-shipyard#27]
I have a job with >1000 tasks, if task id is left to null in jobs.json, when adding task number 1001 (automatically called "dockertask-1000") shipyard fails. The relevant message being: "The specified task already exists."
I suspect the task name becomes too long, the last digit is being silently dropped and thus the task has the exact same name as dockertask-100.

Indeed assigning (short) custom names solves the problem.
If my interpretation is correct I suggest adding a run-time check on validity of task names.

```
2017-01-24 23:01:51,152Z INFO convoy.batch:add_jobs:1894 Adding task: dockertask-1000
Traceback (most recent call last):
  File "/home/adotti/Work/Azure/batch-shipyard/shipyard.py", line 921, in <module>
    cli()
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adotti/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/adotti/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/adotti/Work/Azure/batch-shipyard/shipyard.py", line 741, in jobs_add
    recreate, tail)
  File "/home/adotti/Work/Azure/batch-shipyard/convoy/fleet.py", line 1453, in action_jobs_add
    _BLOBXFER_FILE, recreate, tail)
  File "/home/adotti/Work/Azure/batch-shipyard/convoy/batch.py", line 1895, in add_jobs
    batch_client.task.add(job_id=job.id, task=batchtask)
  File "/home/adotti/.local/lib/python2.7/site-packages/azure/batch/operations/task_operations.py", line 107, in add
    raise models.BatchErrorException(self._deserialize, response)
azure.batch.models.batch_error.BatchErrorException: {'lang': u'en-US', 'value': u'The specified task already exists.\nRequestId:789cbe9f-3006-4325-9ec2-6c094cb64808\nTime:2017-01-25T07:01:50.9582196Z'}

```

**Comment by alfpark** [comment]
@andreadotti Thanks for reporting the issue. Apologies for what you're seeing, the documentation does not appear to be clear enough for this. Task ids must be unique under each job. When you rely on Batch Shipyard to perform task autonaming (i.e., when you leave `id` undefined or `null`), then it only has 1000 effective unique ids in it's default namespace (000 to 999).

I'll make a change so that the default namespace is expanded to five digits and make additional digits append rather than overflow.

**Comment by andreadotti** [comment]
Great, thanks.
Andrea
