### ISSUE TITLE
Scheduling failure error message

### ISSUE THREAD

**Issue by vincenzobaz** [Azure/batch-shipyard#274]
Hello,

I am trying to create a scheduled task.
`jobs.yaml` looks like this:
```
job_specifications:
  - id: test-schedule
    auto_complete: true
    tasks:
    - docker_image: busybox
      command: echo "SCHEDULED TASK RUN"
    recurrence:
      schedule:
        recurrence_interval: 1.00:00:00
```
`busybox` is also listed in `config.yaml`. When I `shipyard jobs add` everything seems fine.
However the jobs fails and `stderr.txt` contains:
```
2019-04-16 08:30:44,969Z DEBUG __main__:_create_credentials:109 creating batch client for account url: https://mybatch.francecentral.batch.azure.com/
Traceback (most recent call last):
  File "/opt/batch-shipyard/recurrent_job_manager.py", line 273, in <module>
    main()
  File "/opt/batch-shipyard/recurrent_job_manager.py", line 243, in main
    batch_client = _create_credentials()
  File "/opt/batch-shipyard/recurrent_job_manager.py", line 112, in _create_credentials
    credentials, base_url=account_service_url)
TypeError: __init__() got an unexpected keyword argument 'base_url'
```

I am wondering if this is a bug in the shipyard code or an issue in my configuration.
If the problem is in my config, what could it be? A more informative error message would be appreciated

**Comment by alfpark** [comment]
Please re-deploy your pool can try again, the fix should be applied in the Batch Shipyard Docker image.

**Comment by vincenzobaz** [comment]
Hello @alfpark, I redeployed and it seems to be working!
Thank you for the quick fix
