### ISSUE TITLE
Pool images update on low priority node

### ISSUE THREAD

**Issue by vincenzobaz** [Azure/batch-shipyard#275]
#### Problem Description
Running `shipyard pool images update` with a low priority node fails
#### Batch Shipyard Version
3.7.0
#### Steps to Reproduce
`shipyard pool images update`
#### Expected Results
Exit code 0
#### Actual Results
```
019-05-07 16:57:39.889 DEBUG - forcing update via SSH due to low priority nodes
2019-05-07 16:57:40.321 INFO - executing command on node supersecretip:50000 with key id_rsa_shipyard
2019-05-07 16:57:40.327 DEBUG - waiting for 1 processes to complete
Traceback (most recent call last):
  File "batch-shipyard/shipyard.py", line 3130, in <module>
    cli()
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "batch-shipyard/shipyard.py", line 1743, in images_update
    singularity_image, ssh)
  File "batch-shipyard/convoy/fleet.py", line 3669, in action_pool_images_update
    singularity_image, force_ssh=ssh)
  File "batch-shipyard/convoy/fleet.py", line 2242, in _update_container_images
    batch_client, config, pool, 'update container images', coordcmd)
  File "batch-shipyard/convoy/fleet.py", line 2032, in _execute_command_on_pool_over_ssh_with_keyed_output
    desc, pool.id))
RuntimeError: failures detected performing update container images on pool: testpool
```
#### Redacted Configuration
`pool.yaml`:
```
pool_specification:
  id: testpool
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
  vm_count:
    dedicated: 0
    low_priority: 1
  vm_size: STANDARD_D3_V2
  ssh:
    username: shipyard
```

**Comment by alfpark** [comment]
I cannot repro this failure. Can you re-run with the `-v` option to see if you get any additional logs? If so, can you please post those?

**Comment by vincenzobaz** [comment]
I changed the `appid`, `directory_id`, `DOCKER_LOGIN_USERNAME` and `DOCKER_LOGIN_PASSWORD` to dummies:

```
config shipyard pool images update -v

2019-05-13 10:16:17.651 DEBUG shipyard:initialize_for_batch:297 initializing for batch actions
2019-05-13 10:16:17.651 DEBUG convoy.aad:create_aad_credentials:255 using aad auth with key, auth=https://login.microsoftonline.com endpoint=https://vault.azure.net directoryid=DIRID appid=APPID
2019-05-13 10:16:18.041 DEBUG convoy.fleet:initialize_globals:353 initialized resources path to: /tmp/batch-shipyard-3.7.0-resources
2019-05-13 10:16:18.041 WARNING convoy.clients:create_all_clients:305 could not create batch management client
2019-05-13 10:16:18.638 DEBUG convoy.fleet:_update_container_images:2190 forcing update via SSH due to low priority nodes
2019-05-13 10:16:18.639 DEBUG convoy.fleet:_execute_command_on_pool_over_ssh_with_keyed_output:1986 executing command: ['sudo', "/bin/bash -c 'export DOCKER_LOGIN_SERVER= && export DOCKER_LOGIN_USERNAME=username && export DOCKER_LOGIN_PASSWORD=pwd && export SINGULARITY_LOGIN_SERVER= && export SINGULARITY_LOGIN_USERNAME=username && export SINGULARITY_LOGIN_PASSWORD=pwd && pushd /mnt/batch/tasks/startup/wd && ./registry_login.sh && popd && docker pull username/dockerimage && docker images --filter dangling=true -q --no-trunc | xargs --no-run-if-empty docker rmi'"]
2019-05-13 10:16:19.032 INFO convoy.crypto:connect_or_exec_ssh_command:211 executing command on node 40.66.57.7:50000 with key id_rsa_shipyard
2019-05-13 10:16:19.039 DEBUG convoy.fleet:_execute_command_on_pool_over_ssh_with_keyed_output:2017 waiting for 1 processes to complete
2019-05-13 10:16:40.086 WARNING convoy.fleet:_execute_command_on_pool_over_ssh_with_keyed_output:2023 return codes: [255]
2019-05-13 10:16:40.086 WARNING convoy.fleet:_execute_command_on_pool_over_ssh_with_keyed_output:2024 stdout: {'tvmps_bbca189fdcdd630071f365657c5e45f058ceab6297bca10d215552ec6ac1a322_p': ''}
2019-05-13 10:16:40.086 WARNING convoy.fleet:_execute_command_on_pool_over_ssh_with_keyed_output:2025 stderr: {'tvmps_bbca189fdcdd630071f365657c5e45f058ceab6297bca10d215552ec6ac1a322_p': 'ssh: connect to host 40.66.57.7 port 50000: Connection refused\n'}
Traceback (most recent call last):
  File "/home/vinz/Downloads/config/batch-shipyard/shipyard.py", line 3130, in <module>
    cli()
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/vinz/Downloads/config/batch-shipyard/.shipyard/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vinz/Downloads/config/batch-shipyard/shipyard.py", line 1743, in images_update
    singularity_image, ssh)
  File "/home/vinz/Downloads/config/batch-shipyard/convoy/fleet.py", line 3669, in action_pool_images_update
    singularity_image, force_ssh=ssh)
  File "/home/vinz/Downloads/config/batch-shipyard/convoy/fleet.py", line 2242, in _update_container_images
    batch_client, config, pool, 'update container images', coordcmd)
  File "/home/vinz/Downloads/config/batch-shipyard/convoy/fleet.py", line 2032, in _execute_command_on_pool_over_ssh_with_keyed_output
    desc, pool.id))
RuntimeError: failures detected performing update container images on pool: testpool
```

**Comment by alfpark** [comment]
Is the node in preempted state? Can you SSH into the node normally?

**Comment by vincenzobaz** [comment]
No, I cannot connect to the machine via ssh

**Comment by alfpark** [comment]
Looks like the node may be preempted. You can issue:

`shipyard pool nodes list`

to confirm.

Note: you can use `shipyard pool ssh` to ssh in without having to mutate your local keys.

**Comment by vincenzobaz** [comment]
if the node is preempted I can only wait right?

I opened the issue because I tried the command multiple times at different times and days and it *never* succeeded

**Comment by alfpark** [comment]
Unfortunately due to how adding a user currently works, even if Batch replaces the preempted node, the user won't be known to the node as the VM is entirely new. You would have to perform that step manually with `shipyard pool user add`. You'll probably want to have a static SSH key (you can just reuse the one that is generated and modify the pool.yaml file).

Improvements to this area are backlogged on #236.

**Comment by vincenzobaz** [comment]
if the node is preempted I can only wait right?

I opened the issue because I tried the command multiple times at different times and days and it *never* succeeded
