### ISSUE TITLE
Can not use premium file storage with shipyard

### ISSUE THREAD

**Issue by maroony** [Azure/batch-shipyard#294]
#### Problem Description
Shipyard doesn't support azure premium file storage created with `az storage account create --kind FileStorage --sku Premium_LRS`

#### Batch Shipyard Version
3.7.0

#### Additional Logs
```
[735] Failed to execute script shipyard
Traceback (most recent call last):
  File "shipyard.py", line 3130, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 1536, in pool_add
  File "shipyard.py", line 311, in initialize_for_batch
  File "convoy/fleet.py", line 425, in fetch_storage_account_keys_from_aad
  File "convoy/storage.py", line 217, in populate_storage_account_keys_from_aad
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by alfpark** [comment]
Unfortunately the documentation around this is not clear (it's only pointed out in the quickstart guide). The linked `storage_account_settings` for `batch_shipyard` in the global config.yaml file must be a general purpose storage account (as it must support blobs, tables and queues which are utilized by various functionality in Batch Shipyard). You can certainly add premium file share accounts as additional storage account for which you can reference as shared volumes or data transfer targets, but the "main" storage account must be general purpose.

```yaml
batch_shipyard:
  storage_account_settings: # this linked storage account must be general purpose
```

We'll improve the documentation here.

**Comment by alfpark** [comment]
I reviewed the code and there is indeed a code defect here with AAD and premium file shares. To work around in the meantime, please specify a storage account key for these types of storage accounts. The prior comment still holds true, however, a general purpose storage account is needed for metadata.
