### ISSUE TITLE
List pools command fails with "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by barborico** [Azure/batch-shipyard#309]
#### Problem Description

Intermittently, the `shipyard pool list` command fails with the exception `TypeError: 'NoneType' object is not iterable`.

#### Batch Shipyard Version

3.7.0

#### Steps to Reproduce

After cloning the batch shipyard repo locally, the command used is:

`
python3 shipyard.py pool list --pool <path to pool config yaml>
`

This does not reliably reproduce the error, but the error has appeared multiple times transiently.

#### Expected Results

```
2019-08-30 17:20:03.986 DEBUG - fetching credentials conf from keyvault
2019-08-30 17:20:04.653 INFO - list of pools
* pool id: ...
```

#### Actual Results

```
2019-08-30 18:40:04.092 DEBUG - fetching credentials conf from keyvault
Traceback (most recent call last):
  File "/opt/batch-shipyard/shipyard.py", line 3130, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/batch-shipyard/shipyard.py", line 1567, in pool_list
    convoy.fleet.action_pool_list(ctx.batch_client, ctx.config)
  File "/opt/batch-shipyard/convoy/fleet.py", line 3221, in action_pool_list
    batch.list_pools(batch_client, config)
  File "/opt/batch-shipyard/convoy/batch.py", line 1215, in list_pools
    for de in err.values:
TypeError: 'NoneType' object is not iterable
```

#### Redacted Configuration
```
pool_specification:
  id: <pool id> 
  vm_configuration:
    platform_image:
      offer: <offer>
      publisher: <publisher>
      sku: <sku>
      native: true
  vm_size: STANDARD_DS2_V2
  vm_count:
    dedicated: 0
    low_priority: 0
  autoscale:
    evaluation_interval: 00:10:00
    formula: '$TargetDedicatedNodes=0;$TargetLowPriorityNodes=2000;'
  remote_access_control:
    starting_port: <port>
    deny:
    - '*'
  block_until_all_global_resources_loaded: false
  additional_node_prep:
    commands:
      post:
      - env > myenvfile
      - docker run --name scan-node-1 --restart unless-stopped --net host --env-file myenvfile -d <image> python3 <script>
      - docker run --name scan-node-2 --restart unless-stopped --net host --env-file myenvfile -d <image> python3 <script>
    environment_variables_keyvault_secret_id: https://<vault name>.vault.azure.net/secrets/<secret name>

```

**Comment by alfpark** [comment]
Related to #307 with low priority preemption.

**Comment by barborico** [comment]
Thanks for jumping on this issue so quickly, Fred! Do you have a ballpark estimate for when this fix will be deployed?

**Comment by alfpark** [comment]
`3.8.2` is anticipated for sometime this week.

**Comment by alfpark** [comment]
Apologies, the next release should be this week.
