### ISSUE TITLE
ERROR - Cascade Docker exited with non-zero exit code: 1

### ISSUE THREAD

**Issue by tswc** [Azure/batch-shipyard#340]
#### Problem Description
FailureExitCode: The task exited with an exit code representing a failure
#### Steps to Reproduce
version 3.8.2
#### Expected Results
The task can not start 
#### Redacted Configuration
```
INSERT RELEVANT YAML FILES
```

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```
[stderr.txt](https://github.com/Azure/batch-shipyard/files/4196355/stderr.txt)
[stdout.txt](https://github.com/Azure/batch-shipyard/files/4196356/stdout.txt)

**Comment by alfpark** [comment]
You will need to attach your `cascade-*.log` files from the `startup/wd` directory. Typically Batch Shipyard will have downloaded these files for you.

**Comment by tswc** [comment]
2020-02-13 04:07:28,679.679Z INFO cascade.py::_setup_logger:155 24:MainThread logger initialized, log file: /mnt/batch/tasks/startup/wd/cascade-docker-20200213T040728.log
2020-02-13 04:07:28,679.679Z INFO cascade.py::main:923 24:MainThread max concurrent downloads: 10
2020-02-13 04:07:28,680.680Z INFO cascade.py::main:942 24:MainThread container mode: DOCKER
2020-02-13 04:07:28,680.680Z DEBUG cascade.py::_unmerge_resources:748 24:MainThread removing node tvmps_7237271648c7e73f8c336661ea7f70708f7d8e34258f8871eb6436ea6b35c179_p from the image table for container mode docker
2020-02-13 04:07:29,362.362Z INFO cascade.py::_unmerge_resources:760 24:MainThread node tvmps_7237271648c7e73f8c336661ea7f70708f7d8e34258f8871eb6436ea6b35c179_p removed from the image table for container mode docker
2020-02-13 04:07:29,461.461Z INFO cascade.py::distribute_global_resources:896 24:MainThread 1 global resources matching container mode "docker"
2020-02-13 04:07:29,719.719Z ERROR cascade.py::write:125 24:MainThread Client-Request-ID=5a0329c2-4e16-11ea-a6d9-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Thu, 13 Feb 2020 04:07:29 GMT, Server-Request-ID=d5297e2a-901e-001a-4323-e2322b000000, HTTP status code=409, Exception=There is already a lease present. ErrorCode: LeaseAlreadyPresent<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.RequestId:d5297e2a-901e-001a-4323-e2322b000000Time:2020-02-13T04:07:29.6884931Z</Message></Error>.

2020-02-13 04:07:29,719.719Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:07:29,783.783Z ERROR cascade.py::write:125 24:MainThread Client-Request-ID=5a2a7710-4e16-11ea-9d3a-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Thu, 13 Feb 2020 04:07:29 GMT, Server-Request-ID=d5297e82-901e-001a-0a23-e2322b000000, HTTP status code=409, Exception=There is already a lease present. ErrorCode: LeaseAlreadyPresent<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.RequestId:d5297e82-901e-001a-0a23-e2322b000000Time:2020-02-13T04:07:29.7525381Z</Message></Error>.

2020-02-13 04:07:29,783.783Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:07:29,846.846Z ERROR cascade.py::write:125 24:MainThread Client-Request-ID=5a3427dc-4e16-11ea-8a97-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Thu, 13 Feb 2020 04:07:29 GMT, Server-Request-ID=d5297ece-901e-001a-4c23-e2322b000000, HTTP status code=409, Exception=There is already a lease present. ErrorCode: LeaseAlreadyPresent<?xml version="1.0" encoding="utf-8"?><Error><Code>LeaseAlreadyPresent</Code><Message>There is already a lease present.RequestId:d5297ece-901e-001a-4c23-e2322b000000Time:2020-02-13T04:07:29.8155828Z</Message></Error>.

2020-02-13 04:07:29,846.846Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:07:29,910.910Z DEBUG cascade.py::_direct_download_resources_async:640 24:MainThread blob lease fed08229-353f-4e52-9539-9f6a5120a434 acquired for resource docker:clobotics.azurecr.io/shipyard:tf1.13-v4
2020-02-13 04:07:29,911.911Z INFO cascade.py::_pull_and_save:533 24:Thread-1 pulling docker image clobotics.azurecr.io/shipyard:tf1.13-v4
2020-02-13 04:07:29,911.911Z DEBUG cascade.py::_pull:518 24:Thread-1 pulling command: docker pull clobotics.azurecr.io/shipyard:tf1.13-v4
2020-02-13 04:07:29,912.912Z ERROR cascade.py::write:125 24:MainThread Executing <Task pending coro=<download_monitor_async() running at cascade.py:824> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f24f53ce978>()] created at /usr/lib/python3.7/asyncio/base_events.py:396> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158] created at /usr/lib/python3.7/asyncio/base_events.py:563> took 0.450 seconds

2020-02-13 04:07:29,912.912Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:10:51,909.909Z DEBUG cascade.py::_pull_and_save:559 24:Thread-1 took 201.997828 sec to pull docker image clobotics.azurecr.io/shipyard:tf1.13-v4
2020-02-13 04:10:51,909.909Z DEBUG cascade.py::_merge_resource:673 24:Thread-1 merging entity {'PartitionKey': 'clobotics$posm-report-v4', 'RowKey': 'bb9a0fc2a961a2c633daf80bc5823f9c7402d930', 'Resource': 'docker:clobotics.azurecr.io/shipyard:tf1.13-v4', 'VmList0': 'tvmps_7237271648c7e73f8c336661ea7f70708f7d8e34258f8871eb6436ea6b35c179_p'} to the image table
2020-02-13 04:10:52,165.165Z ERROR cascade.py::write:125 24:Thread-1 Client-Request-ID=d2ae23c6-4e16-11ea-83ee-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Thu, 13 Feb 2020 04:10:51 GMT, Server-Request-ID=b2a34e50-0002-0037-3123-e28158000000, HTTP status code=409, Exception=Conflict{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:b2a34e50-0002-0037-3123-e28158000000\nTime:2020-02-13T04:10:52.1336424Z"}}}.

2020-02-13 04:10:52,165.165Z ERROR cascade.py::flush:129 24:Thread-1 <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:10:52,466.466Z ERROR cascade.py::write:125 24:Thread-1 Client-Request-ID=d2f096c6-4e16-11ea-9594-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Thu, 13 Feb 2020 04:10:51 GMT, Server-Request-ID=b2a34e7e-0002-0037-5623-e28158000000, HTTP status code=400, Exception=Bad Request{"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:b2a34e7e-0002-0037-5623-e28158000000\nTime:2020-02-13T04:10:52.4348542Z"}}}.

2020-02-13 04:10:52,466.466Z ERROR cascade.py::flush:129 24:Thread-1 <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:10:52,466.466Z ERROR cascade.py::run:389 24:Thread-1 Bad Request
{"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:b2a34e7e-0002-0037-5623-e28158000000\nTime:2020-02-13T04:10:52.4348542Z"}}}
Traceback (most recent call last):
  File "cascade.py", line 676, in _merge_resource
    _STORAGE_CONTAINERS['table_images'], entity=entity)
  File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 933, in insert_entity
    return self._perform_request(request, _extract_etag)
  File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request
    return super(TableService, self)._perform_request(request, parser, parser_args, operation_context)
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureConflictHttpError: Conflict
{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:b2a34e50-0002-0037-3123-e28158000000\nTime:2020-02-13T04:10:52.1336424Z"}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cascade.py", line 387, in run
    self._pull_and_save()
  File "cascade.py", line 562, in _pull_and_save
    self.table_client, self.resource, self.nglobalresources)
  File "cascade.py", line 706, in _merge_resource
    if_match=etag)
  File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1008, in merge_entity
    return self._perform_request(request, _extract_etag)
  File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request
    return super(TableService, self)._perform_request(request, parser, parser_args, operation_context)
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request
    raise ex
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request
    raise ex
  File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request
    HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureHttpError: Bad Request
{"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:b2a34e7e-0002-0037-5623-e28158000000\nTime:2020-02-13T04:10:52.4348542Z"}}}
2020-02-13 04:10:52,533.533Z DEBUG cascade.py::run:409 24:Thread-1 blob lease released for docker:clobotics.azurecr.io/shipyard:tf1.13-v4
2020-02-13 04:10:52,815.815Z CRITICAL cascade.py::download_monitor_async:820 24:MainThread Thread exceptions encountered, terminating
2020-02-13 04:10:52,815.815Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:10:52,815.815Z ERROR cascade.py::write:125 24:MainThread Traceback (most recent call last):

2020-02-13 04:10:52,815.815Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 676, in _merge_resource

2020-02-13 04:10:52,816.816Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,816.816Z ERROR cascade.py::write:125 24:MainThread _STORAGE_CONTAINERS['table_images'], entity=entity)
2020-02-13 04:10:52,816.816Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 933, in insert_entity

2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread return self._perform_request(request, _extract_etag)
2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request

2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread return super(TableService, self)._perform_request(request, parser, parser_args, operation_context)
2020-02-13 04:10:52,817.817Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request

2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request

2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,818.818Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request

2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread HTTPError(response.status, response.message, response.headers, response.body))
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread azure.common
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread .
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread AzureConflictHttpError
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread : 
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread Conflict
{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:b2a34e50-0002-0037-3123-e28158000000\nTime:2020-02-13T04:10:52.1336424Z"}}}
2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread 
During handling of the above exception, another exception occurred:


2020-02-13 04:10:52,819.819Z ERROR cascade.py::write:125 24:MainThread Traceback (most recent call last):

2020-02-13 04:10:52,820.820Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 976, in <module>

2020-02-13 04:10:52,820.820Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,820.820Z ERROR cascade.py::write:125 24:MainThread main()
2020-02-13 04:10:52,820.820Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 952, in main

2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread distribute_global_resources(loop, blob_client, table_client)
2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 899, in distribute_global_resources

2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread loop, blob_client, table_client, nentities))
2020-02-13 04:10:52,821.821Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete

2020-02-13 04:10:52,822.822Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,822.822Z ERROR cascade.py::write:125 24:MainThread return future.result()
2020-02-13 04:10:52,822.822Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 822, in download_monitor_async

2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread raise _THREAD_EXCEPTIONS[0]
2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 387, in run

2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread self._pull_and_save()
2020-02-13 04:10:52,823.823Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 562, in _pull_and_save

2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread self.table_client, self.resource, self.nglobalresources)
2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread   File "cascade.py", line 706, in _merge_resource

2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread if_match=etag)
2020-02-13 04:10:52,824.824Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1008, in merge_entity

2020-02-13 04:10:52,825.825Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,825.825Z ERROR cascade.py::write:125 24:MainThread return self._perform_request(request, _extract_etag)
2020-02-13 04:10:52,825.825Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/cosmosdb/table/tableservice.py", line 1106, in _perform_request

2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread return super(TableService, self)._perform_request(request, parser, parser_args, operation_context)
2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 430, in _perform_request

2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 358, in _perform_request

2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,826.826Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/storageclient.py", line 344, in _perform_request

2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread HTTPError(response.status, response.message, response.headers, response.body))
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread   File "/usr/lib/python3.7/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread     
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread raise ex
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread azure.common
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread .
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread AzureHttpError
2020-02-13 04:10:52,827.827Z ERROR cascade.py::write:125 24:MainThread : 
2020-02-13 04:10:52,828.828Z ERROR cascade.py::write:125 24:MainThread Bad Request
{"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:b2a34e7e-0002-0037-5623-e28158000000\nTime:2020-02-13T04:10:52.4348542Z"}}}
2020-02-13 04:10:52,828.828Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>
2020-02-13 04:10:52,828.828Z ERROR cascade.py::flush:129 24:MainThread <__main__.StandardStreamLogger object at 0x7f24f53a7940>

**Comment by tswc** [comment]
@alfpark Can you please take a look

**Comment by alfpark** [comment]
This issue was fixed in `3.9.0`. Please upgrade to the latest version, and recreate your pool. It is recommended to keep your Shipyard version up to date and periodically recreate your pools to get the latest Batch service fixes. Batch Shipyard has job live migration capability to help you drain and migrate jobs between pools.

This issue was reported and fixed in #327.
