### ISSUE TITLE
"shipyard jobs add" fails in 3.9.1

### ISSUE THREAD

**Issue by themorey** [Azure/batch-shipyard#342]
#### Problem Description
Submitting the "OSUMicroBenchmarks-Infiniband-MVAPICH" recipe fails with Shipyard v3.9.1

#### Batch Shipyard Version
3.9.1

#### Steps to Reproduce
Submit job` shipyard jobs add` in Cloudshell or `../../batch-shipyard-3.9.1-cli-mac-x86_64 jobs add` on Mac

#### Expected Results
```
$ ../../batch-shipyard-3.9.0-cli-mac-x86_64 jobs add
2020-03-06 09:51:12.254 WARNING - pool version metadata mismatch: pool=3.9.1 cli=3.9.0
2020-03-06 09:51:12.255 INFO - Adding job osu-benchmark to pool singularity-mpibench-ompi-autoscale
2020-03-06 09:51:12.744 DEBUG - constructing 1 task specifications for submission to job osu-benchmark
2020-03-06 09:51:12.745 DEBUG - submitting 1 task specifications to job osu-benchmark
2020-03-06 09:51:12.746 DEBUG - submitting 1 tasks (0 -> 0) to job osu-benchmark
2020-03-06 09:51:13.054 INFO - submitted all 1 tasks to job osu-benchmark
```

#### Actual Results
```
$ ../../batch-shipyard-3.9.1-cli-mac-x86_64 jobs add
Traceback (most recent call last):
  File "shipyard.py", line 3136, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 555, in invoke
  File "shipyard.py", line 1971, in jobs_add
  File "convoy/fleet.py", line 4069, in action_jobs_add
  File "convoy/batch.py", line 5244, in add_jobs
  File "convoy/util.py", line 344, in normalize_docker_image_name_for_job
AttributeError: 'NoneType' object has no attribute 'replace'

```
#### Redacted Configuration
https://github.com/Azure/batch-shipyard/tree/master/recipes/OSUMicroBenchmarks-Infiniband-MVAPICH/config

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
Thanks for reporting this issue. This will be fixed in the next release.

**Comment by f-roche** [comment]
@alfpark is there any release planned soon? I just saw that the last one 3.9.1 was end of 2019...
Thanks for this great tool by the way!

**Comment by alfpark** [comment]
Apologies for the release delay. Yes there is one planned to fix up all of the current outstanding issues and to update the API version with various amount of new features exposed.
