### ISSUE TITLE
"The value provided for one of the properties in the request body is invalid." error when trying to create pool

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#53]
I have a recurring job that runs every day, scheduled using an external scheduler. It worked just fine yesterday, but stopped working today. Tried kicking it off again a few times, with the same problem.

This error occurs when the job tries to create the pool (some names changed)

```
2017-03-11T00:18:06.4385430Z Unable to find image 'alfpark/batch-shipyard:cli-latest' locally
2017-03-11T00:18:07.5574940Z cli-latest: Pulling from alfpark/batch-shipyard
2017-03-11T00:18:07.5607490Z 6daefd62341a: Pulling fs layer
2017-03-11T00:18:07.5625380Z 2aa297eab108: Pulling fs layer
2017-03-11T00:18:08.1042870Z 6daefd62341a: Download complete
2017-03-11T00:18:08.3003220Z 6daefd62341a: Pull complete
2017-03-11T00:18:11.6265530Z 2aa297eab108: Verifying Checksum
2017-03-11T00:18:11.6282660Z 2aa297eab108: Download complete
2017-03-11T00:18:14.5793500Z 2aa297eab108: Pull complete
2017-03-11T00:18:14.6183050Z Digest: sha256:7286eeaf0d3cb776acef202d96d16a55987cf31154a03d12ee44bdc2df8c24e7
2017-03-11T00:18:14.6440140Z Status: Downloaded newer image for alfpark/batch-shipyard:cli-latest
2017-03-11T00:18:15.6050450Z 2017-03-11 00:18:15,603Z DEBUG convoy.keyvault:parse_secret_ids:248 fetching batch account key from keyvault
2017-03-11T00:18:16.0461670Z 2017-03-11 00:18:16,042Z DEBUG convoy.keyvault:parse_secret_ids:263 fetching storage account key for link data from keyvault
2017-03-11T00:18:16.3074910Z 2017-03-11 00:18:16,306Z DEBUG convoy.keyvault:parse_secret_ids:263 fetching storage account key for link batch from keyvault
2017-03-11T00:18:16.6545270Z 2017-03-11 00:18:16,653Z DEBUG convoy.keyvault:parse_secret_ids:278 fetching docker registry password for registry myregistry.azurecr.io from keyvault
2017-03-11T00:18:17.3565740Z 2017-03-11 00:18:17,355Z INFO convoy.storage:create_storage_containers:469 creating container: shipyardtor-mybatchaccount-mypool
2017-03-11T00:18:17.5785020Z 2017-03-11 00:18:17,575Z INFO convoy.storage:create_storage_containers:474 creating table: shipyardtorrentinfo
2017-03-11T00:18:17.7681260Z 2017-03-11 00:18:17,766Z INFO convoy.storage:create_storage_containers:477 creating queue: shipyardgr-mybatchaccount-mypool
2017-03-11T00:18:17.9617670Z 2017-03-11 00:18:17,958Z INFO convoy.storage:create_storage_containers:474 creating table: shipyardgr
2017-03-11T00:18:18.0079060Z 2017-03-11 00:18:18,006Z INFO convoy.storage:create_storage_containers:474 creating table: shipyardimages
2017-03-11T00:18:18.0591210Z 2017-03-11 00:18:18,057Z INFO convoy.storage:create_storage_containers:474 creating table: shipyardregistry
2017-03-11T00:18:18.1066530Z 2017-03-11 00:18:18,105Z INFO convoy.storage:create_storage_containers:474 creating table: shipyarddht
2017-03-11T00:18:18.1601350Z 2017-03-11 00:18:18,159Z INFO convoy.storage:create_storage_containers:469 creating container: shipyardrf-mybatchaccount-mypool
2017-03-11T00:18:18.2105060Z 2017-03-11 00:18:18,209Z INFO convoy.storage:_clear_blobs:384 deleting blobs: shipyardtor-mybatchaccount-mypool
2017-03-11T00:18:18.2860930Z 2017-03-11 00:18:18,285Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyardtorrentinfo
2017-03-11T00:18:18.3684180Z 2017-03-11 00:18:18,367Z INFO convoy.storage:clear_storage_containers:452 clearing queue: shipyardgr-mybatchaccount-mypool
2017-03-11T00:18:18.4156300Z 2017-03-11 00:18:18,414Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyardgr
2017-03-11T00:18:18.5136990Z 2017-03-11 00:18:18,512Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyardimages
2017-03-11T00:18:18.5619460Z 2017-03-11 00:18:18,560Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyardperf
2017-03-11T00:18:18.6100800Z 2017-03-11 00:18:18,608Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyardregistry
2017-03-11T00:18:18.7062410Z 2017-03-11 00:18:18,705Z DEBUG convoy.storage:_clear_table:413 clearing table (pk=mybatchaccount$mypool): shipyarddht
2017-03-11T00:18:18.8991810Z 2017-03-11 00:18:18,897Z INFO convoy.storage:_clear_blobs:384 deleting blobs: shipyardrf-mybatchaccount-mypool
2017-03-11T00:18:19.2330150Z 2017-03-11 00:18:19,231Z WARNING convoy.fleet:_adjust_settings_for_pool_creation:1006 forcing shipyard docker image to be used due to VM config, publisher=openlogic offer=centos sku=7.2
2017-03-11T00:18:19.2809030Z 2017-03-11 00:18:19,279Z INFO convoy.storage:_add_global_resource:255 adding global resource: docker:myimage
2017-03-11T00:18:19.7223520Z 2017-03-11 00:18:19,721Z INFO convoy.storage:upload_resource_files:338 uploading file /opt/batch-shipyard/scripts/shipyard_nodeprep.sh as 'shipyard_nodeprep.sh'
2017-03-11T00:18:19.9671350Z 2017-03-11 00:18:19,965Z INFO convoy.storage:upload_resource_files:338 uploading file /opt/batch-shipyard/scripts/docker_jp_block.sh as 'docker_jp_block.sh'
2017-03-11T00:18:20.2068330Z 2017-03-11 00:18:20,205Z INFO convoy.storage:upload_resource_files:338 uploading file /opt/batch-shipyard/scripts/shipyard_blobxfer.sh as 'shipyard_blobxfer.sh'
2017-03-11T00:18:20.4706070Z 2017-03-11 00:18:20,469Z INFO convoy.batch:create_pool:361 Attempting to create pool: mypool
2017-03-11T00:18:20.5340780Z Traceback (most recent call last):
2017-03-11T00:18:20.5356860Z   File "/opt/batch-shipyard/shipyard.py", line 941, in <module>
2017-03-11T00:18:20.5371900Z     cli()
2017-03-11T00:18:20.5385490Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
2017-03-11T00:18:20.5398770Z     return self.main(*args, **kwargs)
2017-03-11T00:18:20.5412370Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
2017-03-11T00:18:20.5428400Z     rv = self.invoke(ctx)
2017-03-11T00:18:20.5441240Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
2017-03-11T00:18:20.5454590Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2017-03-11T00:18:20.5467890Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
2017-03-11T00:18:20.5481400Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2017-03-11T00:18:20.5495210Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
2017-03-11T00:18:20.5508400Z     return ctx.invoke(self.callback, **ctx.params)
2017-03-11T00:18:20.5521630Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
2017-03-11T00:18:20.5535560Z     return callback(*args, **kwargs)
2017-03-11T00:18:20.5548800Z   File "/usr/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
2017-03-11T00:18:20.5561900Z     return ctx.invoke(f, obj, *args[1:], **kwargs)
2017-03-11T00:18:20.5575330Z   File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
2017-03-11T00:18:20.5588100Z     return callback(*args, **kwargs)
2017-03-11T00:18:20.5601120Z   File "/opt/batch-shipyard/shipyard.py", line 607, in pool_add
2017-03-11T00:18:20.5614220Z     ctx.table_client, ctx.config)
2017-03-11T00:18:20.5627110Z   File "/opt/batch-shipyard/convoy/fleet.py", line 1200, in action_pool_add
2017-03-11T00:18:20.5639870Z     _add_pool(batch_client, blob_client, config)
2017-03-11T00:18:20.5653520Z   File "/opt/batch-shipyard/convoy/fleet.py", line 640, in _add_pool
2017-03-11T00:18:20.5666650Z     nodes = batch.create_pool(batch_client, config, pool)
2017-03-11T00:18:20.5679700Z   File "/opt/batch-shipyard/convoy/batch.py", line 365, in create_pool
2017-03-11T00:18:20.5692760Z     batch_client.pool.add(pool)
2017-03-11T00:18:20.5705710Z   File "/usr/lib/python3.5/site-packages/azure/batch/operations/pool_operations.py", line 291, in add
2017-03-11T00:18:20.5718720Z     raise models.BatchErrorException(self._deserialize, response)
2017-03-11T00:18:20.5732820Z azure.batch.models.batch_error.BatchErrorException: {'value': 'The value provided for one of the properties in the request body is invalid.\nRequestId:79b2f4d8-8b47-49fd-a85e-206574727170\nTime:2017-03-11T00:18:20.6184337Z', 'lang': 'en-US'}
```

Any idea why this might be happening? I haven't touched my `pool.json` since yesterday.

My `pool.json`:

```json
{
    "pool_specification": {
        "id": "mypool",
        "vm_size": "STANDARD_A2_V2",
        "vm_count": 10,
        "max_tasks_per_node": 2,

        "publisher": "OpenLogic",
        "offer": "CentOS",
        "sku": "7.2",

        "reboot_on_start_task_failed": true,
        "block_until_all_global_resources_loaded": true
    }
}
```

**Comment by lediur** [comment]
Discovered the issue - apparently `STANDARD_A2_V2` is no longer a valid VM size? I changed it to `STANDARD_A2` and it seems to be working fine.

Is there a list somewhere online where I can see at a glance the VMs that are available for use in Azure Batch? I assumed that all of the available VM types in a region could be used for Batch, but evidently this isn't the case.

**Comment by alfpark** [comment]
General guidance is [here](https://docs.microsoft.com/en-us/azure/batch/batch-api-basics#pool). `STANDARD_A2_V2` should be supported but unfortunately due to a Batch service issue has been temporarily disabled. We'll begin the process of re-enabling this VM size and will update here when it is made available again.

**Comment by lediur** [comment]
Cool, thanks for the update. :+1: A better error message would be super helpful in tracking these things down.

**Comment by alfpark** [comment]
I agree, the error message is not very helpful. We are looking at improving the way error messages flow from the underlying infrastructure stack in Azure to the user so you get useful context.

Apologies for the disruption in your workflow and thanks for your patience.

**Comment by alfpark** [comment]
@lediur You should now be able to deploy `STANDARD_A*_V2` sizes again.
