### ISSUE TITLE
Missing GPU driver config for STANDARD_NV6 machines

### ISSUE THREAD

**Issue by sebastianbk** [Azure/batch-shipyard#71]
I am trying to run the `TensorFlow-GPU` recipe on a `STANDARD_NV6` machine rather than `STANDARD_NC6`. However, when I try to provision a pool using this type of machine I get an error telling me that I need to provide a GPU driver configuration for NV6 machines. When I try with NC6, I am not getting any problems.

I have searched throughout this repository but I cannot seem to any information on GPU configs for NV6 machines. Am I doing something wrong or are NV6 machines simply not supported?

```
> C:\Tools\Azure\batch-shipyard\shipyard.cmd pool add --configdir .
2017-04-21 14:19:39.760 INFO - creating table: shipyardimages
2017-04-21 14:19:39.974 INFO - creating table: shipyarddht
2017-04-21 14:19:40.018 INFO - creating queue: shipyardgr-vrinnocompute-vrinno-gpu
2017-04-21 14:19:40.355 INFO - creating container: shipyardremotefs
2017-04-21 14:19:40.558 INFO - creating container: shipyardrf-vrinnocompute-vrinno-gpu
2017-04-21 14:19:40.599 INFO - creating table: shipyardgr
2017-04-21 14:19:40.654 INFO - creating table: shipyardtorrentinfo
2017-04-21 14:19:40.693 INFO - creating container: shipyardtor-vrinnocompute-vrinno-gpu
2017-04-21 14:19:40.731 INFO - creating table: shipyardregistry
2017-04-21 14:19:40.768 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyardimages
2017-04-21 14:19:40.823 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyarddht
2017-04-21 14:19:40.859 INFO - clearing queue: shipyardgr-vrinnocompute-vrinno-gpu
2017-04-21 14:19:40.896 INFO - deleting blobs: shipyardrf-vrinnocompute-vrinno-gpu
2017-04-21 14:19:40.932 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyardgr
2017-04-21 14:19:40.982 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyardtorrentinfo
2017-04-21 14:19:41.024 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyardperf
2017-04-21 14:19:41.063 INFO - deleting blobs: shipyardtor-vrinnocompute-vrinno-gpu
2017-04-21 14:19:41.096 DEBUG - clearing table (pk=vrinnocompute$vrinno-gpu): shipyardregistry
2017-04-21 14:19:41.136 WARNING - disabling ssh user creation due to script being run from Windows and no public key is specified
2017-04-21 14:19:41.174 INFO - adding global resource: docker:alfpark/tensorflow:1.0.0-gpu
2017-04-21 14:19:41.259 DEBUG - no virtual network settings specified
Traceback (most recent call last):
  File "C:\Tools\Azure\batch-shipyard\shipyard.py", line 1455, in <module>
    cli()
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Tools\Azure\batch-shipyard\shipyard.venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\Azure\batch-shipyard\shipyard.py", line 1045, in pool_add
    ctx.queue_client, ctx.table_client, ctx.config)
  File "C:\Tools\Azure\batch-shipyard\convoy\fleet.py", line 1751, in action_pool_add
    batch_client, blob_client, config
  File "C:\Tools\Azure\batch-shipyard\convoy\fleet.py", line 778, in _add_pool
    blob_client, config, pool_settings.vm_size)
  File "C:\Tools\Azure\batch-shipyard\convoy\fleet.py", line 270, in _setup_nvidia_driver_package
    'configuration').format(vm_size))
RuntimeError: pool consisting of standard_nv6 nodes require gpu driver configuration
```

Here is the `pool.json` file:

```json
{
    "pool_specification": {
        "id": "nc6pool",
        "vm_size": "STANDARD_NC6",
        "vm_count": 1,
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "16.04-LTS",
        "ssh": {
            "username": "docker"
        },
        "reboot_on_start_task_failed": false,
        "block_until_all_global_resources_loaded": true
    }
}
```

I hope you can help me out. Thanks!

**Comment by alfpark** [comment]
@sebastianbk `standard_nv` VMs require a different driver (they must be Nvidia GRID compliant). We're still waiting on the official ones to be made available for Linux. In the meantime, you can fill out the gpu block in `pool.json` with the following preview drivers:

```json
        "gpu": {
            "nvidia_driver": {
                "source": "https://azuregpu.blob.core.windows.net/nv-drivers/NVIDIA-Linux-x86_64-361.45.09-grid.run"
            }
        }
```

Note that these are preview drivers and the code path for installing these drivers has not been fully verified (e.g., you may encounter `start_task_failed` when the compute pool is being provisioned or some other issue). Also, NC is typically recommended over NV for any compute-offload (K80, although a prior generation than the M60, is typically faster for compute tasks: more memory, more bandwidth, much faster double precision FP).

**Comment by sebastianbk** [comment]
Hi @alfpark. Thanks a lot for your answer. I will look forward to the availability of the GRID driver then.

I will stick with NC-series VMs for now.
