### ISSUE TITLE
shipyard does not exit on node allocation failure

### ISSUE THREAD

**Issue by mkiernan** [Azure/batch-shipyard#95]
When shipyard times out after being unable to allocate nodes, instead of exiting, it errors out and then continues to attempt to execute a job, and waits indefinitely: 

2017-06-02 08:12:50,372 DEBUG convoy.batch:_block_for_nodes_ready:332 waiting for 1 dedicated nodes and 0 low priority nodes to reach desired state
Traceback (most recent call last):
  File "/home/uniqnam/batch/repos/batch-shipyard/shipyard.py", line 1530, in <module>
    cli()
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/uniqnam/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/uniqnam/batch/repos/batch-shipyard/shipyard.py", line 1065, in pool_add
    ctx.queue_client, ctx.table_client, ctx.config)
  File "/home/uniqnam/batch/repos/batch-shipyard/convoy/fleet.py", line 1931, in action_pool_add
    batch_client, blob_client, config
  File "/home/uniqnam/batch/repos/batch-shipyard/convoy/fleet.py", line 987, in _add_pool
    nodes = batch.create_pool(batch_client, config, pool)
  File "/home/uniqnam/batch/repos/batch-shipyard/convoy/batch.py", line 420, in create_pool
    return wait_for_pool_ready(batch_client, config, pool.id)
  File "/home/uniqnam/batch/repos/batch-shipyard/convoy/batch.py", line 367, in wait_for_pool_ready
    settings.pool_settings(config).reboot_on_start_task_failed)
  File "/home/uniqnam/batch/repos/batch-shipyard/convoy/batch.py", line 258, in _block_for_nodes_ready
    pool.id, os.linesep.join(errors)))
RuntimeError: Fatal resize errors encountered for pool h16pool: code=AllocationTimedout msg=Desired number of dedicated nodes could not be allocated as the resize timeout was reached
+ /home/uniqnam/batch/repos/batch-shipyard/shipyard jobs add --configdir config --tail stdout.txt
2017-06-02 08:13:01,592 INFO - Adding job uniqnamjob to pool h16pool
2017-06-02 08:13:02,576 DEBUG - submitting 10 tasks (0 -> 9) to job uniqnamjob
2017-06-02 08:13:03,063 INFO - submitted all 10 tasks to job uniqnamjob
2017-06-02 08:13:03,063 DEBUG - attempting to stream file stdout.txt from job=uniqnamjob task=dockertask-00031

**Comment by alfpark** [comment]
It looks like you are calling `jobs add` after your pool allocation. Batch Shipyard has no logic to allocate a pool and then submits jobs in one command. These are separate, distinct actions (`pool add` and `jobs add`) - Batch Shipyard does indeed exit as you can see from the `RuntimeError` thrown above and you are explicitly invoking `jobs add` after that exception is thrown. If you are invoking these actions in a shell script, make sure you are checking the return/exit codes of each action or use shell convenience features like (`set -e` in bash). Calling `jobs add` with no available nodes in the pool will result in what you are seeing.

You can either increase the pool `resize_timeout` from the default of 15 minutes to something larger or call `pool resize --wait` after you receive an `AllocationTimedout` failure prior to submitting `jobs add`.

**Comment by mkiernan** [comment]
<face palm> - you are correct, I forgot I had embedded the whole thing  a script - I thought shipyard was doing this, but it was my script. Apologies.
